### PR TITLE
Fix WebSocket subscription tests

### LINKED ISSUE #26: Fix tests for WebSocket subscriptions
There are a few timing issues in there, and some minor server changes affect what we should look for.

### PR DESCRIPTION
**Pull request by AlexBlumer**
Fixes #26 

The `requestId` changes are due to PR Vantiq/ag2rs#7934, It removed the field from the subscription's return, presumably because the value is also available  in the header `X-Request-Id`.

### CODE REVIEW

File: src/test/java/io/vantiq/client/intg/VantiqIntegrationTest.java [hunk 1]
```diff
@@ -431,11 +431,15 @@ public void testSubscribeReliableTopic() throws Exception {
         vantiq.subscribe(Vantiq.SystemResources.TOPICS.value(), "/test/topic", null, callback, params);
         callback.waitForCompletion();
         LinkedTreeMap msg = (LinkedTreeMap) callback.getMessage().getBody();
-        String ackId = msg.get("subscriptionName").toString();
-        String requestId = msg.get("requestId").toString();
-        callback.reset();
-        callback.waitForCompletion();
-        assertThat("Connected", callback.isConnected(), is(true));
+        assertThat(msg.get("subscriptionName"), instanceOf(String.class));
+        assertThat(callback.getMessage().getHeaders().get("X-Request-Id"), instanceOf(String.class));
```
Comment (AlexBlumer) [inline src/test/java/io/vantiq/client/intg/VantiqIntegrationTest.java:435]: This way we don't get an NPE/cast error if the values are wrong. The one test that uses these values now assigns them after the asserts.

File: src/test/java/io/vantiq/client/intg/VantiqIntegrationTest.java [hunk 2]
```diff
@@ -431,11 +431,15 @@ public void testSubscribeReliableTopic() throws Exception {
...
+    
+        // Sometimes the connection occurs during the validations above. Check for completion only if it's not connected
+        if (!callback.isConnected()) {
+            callback.reset();
+            callback.waitForCompletion();
+            assertThat("Connected", callback.isConnected(), is(true));
+        }
```
Comment (AlexBlumer) [inline src/test/java/io/vantiq/client/intg/VantiqIntegrationTest.java:442]: If the connection message comes fast enough, it will occur before the reset. The assert here will then fail since `reset()` clears all the flags used by the test callback class.

Comment (rblumer4) [reply src/test/java/io/vantiq/client/intg/VantiqIntegrationTest.java:442]: Might put the assert outside of the IF, just so it is always checked.  Makes test clearer to me.
```suggestion
        // Sometimes the connection occurs during the validations above. 
        // So wait for completion only if it's not already connected
        if (!callback.isConnected()) {
            callback.reset();
            callback.waitForCompletion();
        }
        assertThat("Connected", callback.isConnected(), is(true));
```

**Review by rblumer4 — APPROVED** [review]
LGTM.  
One nit about waitForCompletion IFs
